### ISSUE TITLE
Récupérer les événements depuis Eventbrite.

### ISSUE THREAD

**Issue by makerslabemlyon** [emlyon/makerslab#72]
Aujourd'hui, on liste les événements du lab depuis le calendrier "webagenda" de la Gmail du makerslab.

Ça utilise un script qui se trouve ici : https://script.google.com/home/projects/1G91frmtnwV2BumroKcl-kGl2y7UE3lGYrg4xMX0JhCkEQ01LnTGQhLTM/edit

On souhaite tester une gestion des événements depuis Eventbrite en utilisant leur API.

**Comment by Jetinho** [comment]
Done in #74, #75, #76, #77 and #78
